---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: alidns-webhook-zverse-letsencrypt
spec:
  acme:
    email: astro24002@163.com
    privateKeySecretRef:
      name: alidns-webhook-zverse-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            config:
              accessTokenSecretRef:
                key: access-token
                name: alidns-webhook-zverse-secrets
              regionId: cn-beijing
              secretKeySecretRef:
                key: secret-key
                name: alidns-webhook-zverse-secrets
            groupName: ska.zverse.space
            solverName: alidns-solver
