kind: ConfigMap
apiVersion: v1
metadata:
  name: xrootd-checksum
  namespace: xrootd
  uid: c48dc084-33de-4b9d-9cbe-377dad7199e1
  resourceVersion: '254401859'
  creationTimestamp: '2024-11-26T07:19:26Z'
data:
  checksumscript.sh: |-
    #!/bin/bash

    CKSLINE=$(/usr/bin/xrdadler32 "$1")

    # Check if the command was successful
    if [ $? -eq 0 ]; then
        # Print the value of CKS followed by a new line
        CKS=$(echo ${CKSLINE} | awk '{print $1}')
        echo "$CKS"
        # Exit with return code 0
        exit 0
    else
        # If the command failed, exit with the error code
        exit 1
    fi
