---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: src-net-preparedata
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://artefact.skao.int/repository/helm-internal/
    chart: ska-src-dm-local-data-preparer
    targetRevision: 0.3.6
    helm:
      releaseName: src-net-preparedata
      valuesObject:
        localPreparerCore:
          image:
            registry: artefact.skao.int
            image: dpapi-core
            tag: 0.3.6
            pullPolicy: Always
        celeryWorker:
          image:
            registry: artefact.skao.int
            image: dpapi-celery
            tag: 0.3.6
            pullPolicy: Always
        service:
          type: NodePort
          port: 8000
        rabbitmqService:
          type: ClusterIP
          port: 5672
          managementPort: 15672
        # Only used for the cavern approach, secret name should be `cavern-api-key`.
        #secrets:
        #  cavern:
        #    existingSecret: true
        env:
          ABS_PATH_USER_AREA_ROOT: /users/cavern/home
          ABS_PATH_RSE_ROOT: /rse
          ABS_PATH_CELERY_RESULTS: /var/celery/results
          SUPPORTED_APPROACHES: copy
          DEFAULT_APPROACH: copy
        pvc:
          rse: "xrootd-preparedata-static-pvc"
          rsePath: "/rse"
          cavern: "skaha-preparedata-static-pvc"
          cavernPath: "/users"
          celeryCache: "preparedata-celery-cache-pvc"
          celeryCachePath: "/var/celery/results"
  destination:
    server: https://kubernetes.default.svc
    namespace: preparedata
