---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-site-capabilities-lua-config
  namespace: gatekeeper
data:
  site-capabilities.lua: |
    local _M = {}

    local cjson = require "cjson"
    local response = require "conf.response"
    local services_cache = {}

    -- Function to read content from a file
    local function read_file(path)
        local file = io.open(path, "r")
        if not file then
            ngx.log(ngx.ERR, "Could not open file: ", path)
            return nil
        end
        local content = file:read("*a")
        file:close()
        return content:gsub("%s+$", "")  -- Trim any trailing whitespace
    end

    -- Function to fetch the access token
    local function fetch_site_capabilities_api_access_token()
        local http = require "resty.http"
        local httpc = http.new()

        local client_id = read_file("/etc/credentials/client_id")
        local client_secret = read_file("/etc/credentials/client_secret")
        local scope = "{{ .Values.gatekeeper.site_capabilities_gatekeeper_client_scopes }}"
        local audience = "{{ .Values.gatekeeper.site_capabilities_gatekeeper_client_audience }}"

        local credentials = ngx.encode_base64(client_id .. ":" .. client_secret)
        local args = {
            grant_type = "client_credentials",
            scope = scope,
            audience = audience,
        }

        -- Make a request against IAM to fetch this token using a client_credentials grant
        local res, err = httpc:request_uri("{{ .Values.gatekeeper.iam_token_endpoint }}", {
            method = "POST",
            body = ngx.encode_args(args),
            headers = {
                ["Authorization"] = "Basic " .. credentials,
                ["Content-Type"] = "application/x-www-form-urlencoded",
            },
            ssl_verify = true
        })

        if not res or res.status ~= 200 then
            return nil, err
        end

        ngx.log(ngx.NOTICE, "Successfully retrieved access token")
        local result = cjson.decode(res.body)

        return result.access_token
    end

    -- Function to fetch a service description by ID
    local function fetch_service_description_by_id(id, access_token)
        local http = require "resty.http"
        local httpc = http.new()

        -- Query the Site Capabilities API for service definitions
        local url = "{{ .Values.gatekeeper.site_capabilities_api_get_service_by_id_endpoint }}" .. id
        local res, err = httpc:request_uri(url, {
            method = "GET",
            headers = {
                ["Authorization"] = "Bearer " .. access_token,
            },
            ssl_verify = true
        })

        if not res or res.status ~= 200 then
            return nil, err
        end

        ngx.log(ngx.NOTICE, "Successfully retrieved service")
        local result = cjson.decode(res.body)

        -- Cache the fetched service with a TTL
        services_cache[id] = { service = result, expiration = ngx.now() + {{ .Values.gatekeeper.services_cache_ttl }} }

        return result
    end

    -- Function to check if a cached service has expired
    local function is_cached_service_valid(id)
        local entry = services_cache[id]
        if entry and entry.expiration > ngx.now() then
            return true
        end
        return false
    end

    -- Function to look up a service by ID
    function _M.lookup_service_by_id(id)
        -- Check if the service is in the cache and if the cache is still valid for this service
        if services_cache[id] and is_cached_service_valid(id) then
            ngx.log(ngx.NOTICE, "Returning cached service for ID: " .. id)
            return services_cache[id].service
        else
            -- If cache is invalid remove the expired entry
            ngx.log(ngx.NOTICE, "Either entry for service in cache doesn't exist or has expired, will query")
            services_cache[id] = nil
        end

        -- Fetch an access token
        local access_token, err = fetch_site_capabilities_api_access_token()
        if not access_token then
            local error_message = err and err or "An unknown error occurred"
            ngx.log(ngx.ERR, "Failed to retrieve access token from IAM: ", error_message)
            response.send("ERROR", "Failed to retrieve access token from IAM: " .. error_message,
                    ngx.HTTP_INTERNAL_SERVER_ERROR)
        end

        -- Fetch the service description by ID
        local service, err = fetch_service_description_by_id(id, access_token)
        if not service then
            local error_message = err and err or "An unknown error occurred"
            ngx.log(ngx.ERR, "Failed to retrieve service description from Site Capabilities API: ", error_message)
            response.send("ERROR", "Failed to retrieve service description from Site Capabilities API: " ..
                    error_message, ngx.HTTP_INTERNAL_SERVER_ERROR)
        end

        return service
    end

    return _M
