---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ska-src-gatekeeper-echo
  name: ska-src-gatekeeper-echo
  namespace: gatekeeper
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ska-src-gatekeeper-echo
  type: NodePort
