---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - path: clusters/ska132/applications/basic-components/cluster-issuer
      repoURL: https://gitlab.com/ska-telescope/src/deployments/cnsrc/ska-src-cnsrc-services-cd.git
      targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: basic-components
