---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.16.4
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true
            keep: true
          image:
            repository: m.daocloud.io/quay.io/jetstack/cert-manager-controller
          prometheus:
            enabled: false
          webhook:
            image:
              repository: m.daocloud.io/quay.io/jetstack/cert-manager-webhook
            securePort: 10250
          cainjector:
            image:
              repository: m.daocloud.io/quay.io/jetstack/cert-manager-cainjector
          acmesolver:
            image:
              repository: m.daocloud.io/quay.io/jetstack/cert-manager-acmesolver
          startupapicheck:
            image:
              repository: m.daocloud.io/quay.io/jetstack/cert-manager-startupapicheck
      destination:
        server: https://kubernetes.default.svc
        namespace: basic-components
